export { RemoteRestAdapter, type RemoteConfig } from "./remote.js";
export {
  TauriFsAdapter,
  isTauri,
  openVaultFolderInExplorer,
  openExternalUrl,
  revealVaultEntry,
  writeClipboardFiles,
  readClipboardFiles,
  hasClipboardFiles,
  clipboardFilesAreCut,
  clearClipboardFiles,
  copyPathsIntoDir,
  movePathsIntoDir,
  pickFolder,
  listDirectory,
  readExternalText,
  readExternalBinary,
  externalPathExists,
  getAbsoluteFilesystemAssetUrl,
  watchVaultFolder,
  unwatchVaultFolder,
  listenOsFileDrop,
  type ExternalFsEntry,
} from "./tauri.js";
